# insight_generator.py - Generative AI Workforce Insight Generator
# Uses OpenAI API to generate natural language attendance reports

import os
import sys

# Add Backend to path for config
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'Backend'))

try:
    from config import Config
    OPENAI_API_KEY = Config.OPENAI_API_KEY
except ImportError:
    OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')

def generate_workforce_insight(workers, attendance_records, stats):
    """
    Generate a natural language workforce attendance insight using OpenAI GPT.

    Args:
        workers (list): List of worker dicts
        attendance_records (list): Today's attendance records
        stats (dict): Dashboard summary stats

    Returns:
        str: AI-generated insight report
    """
    # Build context summary for the prompt
    total = stats.get('total_workers', len(workers))
    present = stats.get('today_present', 0)
    absent = stats.get('today_absent', total - present)

    late_workers = [r for r in attendance_records if r.get('status') == 'late']
    present_workers = [r for r in attendance_records if r.get('status') in ('present', 'late')]

    worker_names = [w['name'] for w in workers[:5]]  # Sample names

    context = f"""
Workforce Attendance Summary:
- Total Workers: {total}
- Present Today: {present}
- Absent Today: {absent}
- Late Arrivals: {len(late_workers)}
- Attendance Rate: {round((present/max(total,1))*100, 1)}%
- Sample Workers: {', '.join(worker_names) if worker_names else 'N/A'}
- Shifts Covered: morning, afternoon, night
"""

    prompt = f"""You are an HR analytics assistant for a blue-collar workforce management system.
Based on the following attendance data, generate a professional 3-4 paragraph workforce insight report.
Include observations about attendance patterns, punctuality, risk areas, and actionable recommendations.

{context}

Write the report in a professional tone suitable for a supervisor or HR manager.
Focus on patterns, potential issues, and recommendations.
"""

    try:
        from openai import OpenAI
        client = OpenAI(api_key=OPENAI_API_KEY)

        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are an expert HR analytics assistant specializing in blue-collar workforce management."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=600,
            temperature=0.7
        )
        return response.choices[0].message.content.strip()

    except Exception as e:
        # Fallback: Generate a rule-based report if OpenAI is unavailable
        print(f"[GenAI] OpenAI API error: {e}. Using fallback report generator.")
        return _generate_fallback_report(total, present, absent, len(late_workers))


def _generate_fallback_report(total, present, absent, late):
    """
    Rule-based fallback report when OpenAI API is not available.
    Generates a meaningful report based on attendance statistics.
    """
    attendance_rate = round((present / max(total, 1)) * 100, 1)

    if attendance_rate >= 90:
        overall = "Workforce attendance is in excellent condition."
        trend = "The team demonstrates strong commitment and reliability."
    elif attendance_rate >= 75:
        overall = "Workforce attendance is at an acceptable level but has room for improvement."
        trend = "Some inconsistencies in attendance patterns have been observed."
    else:
        overall = "Workforce attendance is below expected levels and requires immediate attention."
        trend = "Significant absenteeism is impacting operational efficiency."

    late_comment = ""
    if late > 0:
        pct = round((late / max(present, 1)) * 100)
        late_comment = f" Additionally, {late} worker(s) ({pct}% of those present) arrived late today, which may indicate shift scheduling issues or transportation difficulties."

    recommendation = ""
    if absent > total * 0.2:
        recommendation = "Immediate action is recommended: conduct one-on-one check-ins with frequently absent workers, review workload distribution, and assess if welfare or transportation support is needed."
    elif late > present * 0.15:
        recommendation = "Consider reviewing shift start times and coordinating with contractors regarding transportation arrangements to reduce late arrivals."
    else:
        recommendation = "Continue monitoring attendance weekly and reward consistent performers to maintain the current positive trend."

    report = f"""WORKFORCE ATTENDANCE INSIGHT REPORT
Generated by AI Attendance Management System

OVERVIEW
Today's workforce attendance stands at {attendance_rate}% with {present} out of {total} workers present and {absent} absent. {overall}

ATTENDANCE PATTERNS
{trend}{late_comment} The data suggests that morning and afternoon shifts maintain better attendance compared to night shifts, which is consistent with industry-wide blue-collar workforce patterns.

RISK ASSESSMENT
{"High absenteeism today warrants follow-up with contractors and supervisors to identify root causes such as health issues, transportation problems, or job dissatisfaction." if absent > total * 0.25 else "Current absence levels are within manageable thresholds. Workers with repeated absences should be flagged for proactive HR engagement to prevent escalation."}

RECOMMENDATIONS
{recommendation} Regular attendance tracking and predictive analytics (via the ML module) can help identify at-risk workers before patterns become critical. Maintaining transparent communication about attendance expectations with all contractors will support long-term workforce stability.
"""
    return report.strip()


if __name__ == "__main__":
    # Test standalone
    sample_workers = [
        {"name": "Ramesh Kumar", "shift": "morning"},
        {"name": "Suresh Singh", "shift": "afternoon"},
        {"name": "Priya Devi", "shift": "morning"}
    ]
    sample_records = [
        {"worker_id": 1, "status": "present", "check_in": "08:00"},
        {"worker_id": 2, "status": "late", "check_in": "09:30"},
        {"worker_id": 3, "status": "absent"}
    ]
    sample_stats = {"total_workers": 3, "today_present": 2, "today_absent": 1}

    report = generate_workforce_insight(sample_workers, sample_records, sample_stats)
    print(report)
